### ISSUE TITLE
How do I connect with my MIKROTIK

### ISSUE THREAD

**Issue by toliano** [ibnux/phpmixbill#18]
Am really in love with this, but please how do I connect it with my Mikrotik?
Currently have input my MIKROTIK credentials under Network/router.

But still not connecting to the mikrotik board. Thanks in advance

**Comment by markunyil** [comment]
You can try to update php pear2 netrouterOS https://github.com/pear2/Net_RouterOS to folder system/PEAR2

**Comment by Chimunet** [comment]
Hello everyone. Excuse me for my english. Use Google Translate. I'm From Argentina ... This is the solution for PHPMIXBILL to work with API in RouterOS v6.43+ versions, specifically it was tested with RouterOS v6.47.4 On December 16, 2020 ...

I use Ubuntu 18.04, but it is valid for Windows Server or the operating system they use.

Edit the file found in the following path, With your favorite text editor, As Administrator or Root:

phpmixbill-master/system/autoload/PEAR2/Net/RouterOS/Client.php

In my case I use gedit:

~$ sudo gedit phpmixbill-master/system/autoload/PEAR2/Net/RouterOS/Client.php

Client.php, is the file to edit.

As of line 275, Original, it looks like this:

275 $request->setArgument(
276 'response',
277 '00' . md5(
278 chr(0) . $password
279 . pack('H*', $response->getProperty('ret'))
280 )
281 );
282 $request->send($com);
284 $response = new Response($com, false, $timeout);
285 return $response->getType() === Response::TYPE_FINAL
286 && null === $response->getProperty('ret');
287 }

They must edit the lines so that they are as follows:

275 $request->setArgument('password', $password);
276 $request->send($com);
277 $response = new Response($com, false, $timeout);
278 return $response->getType() === Response::TYPE_FINAL
279 && null === $response->getProperty('ret');
280 }

Then save and restart the LAMP server in my case, Apache2

~$ sudo systemctl restart apache2

With this we managed to adapt the operation of PEAR2, as established by Mikrotik in the most recent updates of RouterOS and API, explained in this link:

https://wiki.mikrotik.com/wiki/Manual:API#Initial_login
