### ISSUE TITLE
Unable to connect to router

### ISSUE THREAD

**Issue by Csun-blip** [ibnux/phpmixbill#19]
In the hotspot plan (services) there is always this error that : unable to connect to the router.

**Comment by cahpunke** [comment]
u try download phpmixbill https://github.com/ibnux/phpmixbill/tree/mikrotikOS.6.43

**Comment by Csun-blip** [comment]
I am using phpmixbill for the test purpose and trying to add hotspot plan
and I gave a non existing router ip address which result in unable to
connect router, should I give the valid ip address of the router or is this
some error of the phpmixbill.

**Comment by Chimunet** [comment]
Hello everyone. Excuse me for my english. Use Google Translate. I'm From Argentina ... This is the solution for PHPMIXBILL to work with API in RouterOS v6.43+ versions, specifically it was tested with RouterOS v6.47.4 On December 16, 2020 ...

I use Ubuntu 18.04, but it is valid for Windows Server or the operating system they use.

Edit the file found in the following path, With your favorite text editor, As Administrator or Root:

phpmixbill-master/system/autoload/PEAR2/Net/RouterOS/Client.php

In my case I use gedit:

# sudo gedit phpmixbill-master/system/autoload/PEAR2/Net/RouterOS/Client.php

Client.php, is the file to edit.

As of line 275, Original, it looks like this:

275        $request->setArgument(
276            'response',
277            '00' . md5(
278                chr(0) . $password
279                . pack('H*', $response->getProperty('ret'))
280            )
281        );
282        $request->send($com);
284        $response = new Response($com, false, $timeout);
285        return $response->getType() === Response::TYPE_FINAL
286            && null === $response->getProperty('ret');
287    }

They must edit the lines so that they are as follows:

275       $request->setArgument('password', $password);
276       $request->send($com);
277       $response = new Response($com, false, $timeout);
278       return $response->getType() === Response::TYPE_FINAL
279            && null === $response->getProperty('ret');
280    }

Then save and restart the LAMP server in my case, Apache2

# systemctl restart apache2

With this we managed to adapt the operation of PEAR2, as established by Mikrotik in the most recent updates of RouterOS and API, explained in this link:

https://wiki.mikrotik.com/wiki/Manual:API#Initial_login

**Comment by Mitigoa** [comment]
thank you so much this works
